### ISSUE TITLE
custom HTML elements

### ISSUE THREAD

**Issue by xpepermint** [atom/language-css#17]
Example:

``` css
page-header {
    display: block;
    background: #ff0000;
    height: calc(100% - 100px);
    overflow: auto;
}
```

The `page-header` is not colored correctly in atom.
