### ISSUE TITLE
Add :focus-visible and :user-invalid pseudoclasses

### ISSUE THREAD

**Issue by alexr00** [atom/language-css#180]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

`focus-visible` and `user-invalid` are not scoped as `entity.other.attribute-name.pseudo-class.css`

### Steps to Reproduce

1. Write the following CSS

```css
a:hover         { color: red; }
a:focus         { color: red; }
a:focus-visible { color: red; }
a:invalid       { color: red; }
a:user-invalid  { color: red; }
```

**Expected behavior:** all of the pseudoclasses are scoped as `entity.other.attribute-name.pseudo-class.css`.

**Actual behavior:** `focus-visible` and `user-invalid` are scoped as `entity.name.tag.custom.css`

**Reproduces how often:** 100%

### Versions

Commit 339e9600ce4e024fa97a711d6330e3b5344fcbdc

Originally from @wojtekmaj in https://github.com/microsoft/vscode/issues/124369
