### ISSUE TITLE
CSS code highlighting on some more properties not working

### ISSUE THREAD

**Issue by go-commit-code** [atom/language-css#194]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Some missing property highlighting has already been reported (#189, #190, #192),
But I thought I'd go through [MDN css reference](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference) to see if there are more.

I have only tested on vscode, but I'm assuming the grammer is up to date. (updated `2 Nov 2021`)

The following properties are missing syntax highlighting:

Non-experimental properties:
- `border-block`
- `border-block-color`
- `border-block-style`
- `border-block-width`
- `border-inline`
- `border-inline-color`
- `border-inline-style`
- `border-inline-width`
- `color-scheme`
- `content-visibility`
- `counter-set`
- `forced-color-adjust`
- `offset-rotate`
- `print-color-adjust`
- `text-decoration-thickness`
- `text-underline-offset`
- `vector-effect` (svg)

Experimental properties:
- `inherits`
- `math-style`
- `overflow-clip-margin`
- `syntax`

Behind experimantal flag:
- `align-tracks`
- `animation-timeline`
- `justify-tracks`
- `line-height-step`

Not implemented in any browser:
- `margin-trim`
- `masonry-auto-flow`

Deprecated:
- `viewport-fit`

No MDN docs:
- `block-overflow`
- `input-security`

### Steps to Reproduce

Reproduces with this snippet:
```css
div {
	/* Non-experimental properties */
	border-block: initial;
	border-block-color: initial;
	border-block-style: initial;
	border-block-width: initial;
	border-inline: initial;
	border-inline-color: initial;
	border-inline-style: initial;
	border-inline-width: initial;
	color-scheme: initial;
	content-visibility: initial;
	counter-set: initial;
	forced-color-adjust: initial;
	offset-rotate: initial;
	print-color-adjust: initial;
	text-decoration-thickness: initial;
	text-underline-offset: initial;

	/* Experimental properties */
	inherits: initial;
	math-style: initial;
	overflow-clip-margin: initial;
	syntax: initial;

	/* Behind experimantal flag */
	align-tracks: initial;
	animation-timeline: initial;
	justify-tracks: initial;
	line-height-step: initial;

	/* Not implemented in any browser */
	margin-trim: initial;
	masonry-auto-flow: initial;

	/* Deprecated */
	viewport-fit: initial;

	/* No MDN docs */ 
	block-overflow: initial; /* I think this has been renamed to `overflow-block` */
	input-security: initial;

	/* svg */
	vector-effect: initial; /* no compatibility table on MDN, but works on chrome */
}
```

**Expected behavior:**

The properties have syntax highlighting

**Actual behavior:**

The properties don't have syntax highlighting

**Reproduces how often:**

100%
