### ISSUE TITLE
Cannot comment code that starts with a comment

### ISSUE THREAD

**Issue by eddiemonge** [atom/language-css#39]
Selecting all the following code and then trying to comment it out does nothing. I would expect it to comment out the css code.

```css
/* General Overrides */

.codelab code.prettyprint {
  color: white; /* default color in case offline */
}
```
