### ISSUE TITLE
Media queries over multiple lines

### ISSUE THREAD

**Issue by thomaslindstrom** [atom/language-css#4]
Hi! Media queries don't work over multiple lines, even when separated with a comma. It is then treated as normal text.

``` css
    @media (-webkit-min-device-pixel-ratio: 2),
           (min-resolution: 192dpi) {
        width: 200px;
        height: 200px; 
    }
```
