### ISSUE TITLE
Standalone attribute selector missing

### ISSUE THREAD

**Issue by smutnyleszek** [atom/language-css#43]
Attribute selectors are not highlighted when are not prefixed with anything.

So these are ok:

``` CSS
span[foo] { font-weight: bold; }
a[href*="bar"] { font-weight: bold; }
```

And these are not ok:

``` CSS
[foo] { font-weight: bold; }
[class~="bar"] { font-weight: bold; }
```

The weird thing is that I couldn't find any example of standalone attribute selector in specifications, but they work perfectly. All the examples uses combined selectors like `h1[foo]`. It seems that `[foo]` is the same as `*[foo]`.
