### ISSUE TITLE
Add support for custom properties

### ISSUE THREAD

**Issue by colinmeinke** [atom/language-css#48]
As a syntax theme author I would love support for [CSS custom properties](http://www.w3.org/TR/css-variables/) which allows the following syntax in CSS:

``` css
:root {
  --bg-color: rgb( 255, 255, 255 );
}

body {
  background-color: var( --bg-color );
}
```

It would be great to get the variable class for `--bg-color` so I can style consistently between CSS, Sass and Less.
