### ISSUE TITLE
Prepare for the future of CSS

### ISSUE THREAD

**Issue by thomaslindstrom** [atom/language-css#51]
The Atom CSS language parser is aging fast with the advent of `postcss`, and, notably, [http://cssnext.io/](http://cssnext.io/). 

The biggest features are _[nesting](http://cssnext.io/features/#nesting)_, _[custom selectors](http://cssnext.io/features/#custom-selectors)_ and _[custom variables](http://cssnext.io/features/#custom-properties-var)_, which already has an issue here: #48.

“The future of CSS” has, I'd argue, three key features:
- [ ] [Nesting](http://cssnext.io/features/#nesting)
- [ ] [Custom selectors](http://cssnext.io/features/#custom-selectors)
- [x] [Custom variables](http://cssnext.io/features/#custom-properties-var)

The implementation of said features would advance the parser and prepare it for what's to come, and, in part, what's already here.

**Comment by lee-dohm** [comment]
What exactly are you proposing? What would I, or anyone else interested in fixing this, have to do to consider this Issue closed?

**Comment by thomaslindstrom** [comment]
This issue could obviously have been broken down into more, separate, issues. However, as the title suggests, “preparing for the future of CSS” could be broken down into a few key features:   *[nesting](http://cssnext.io/features/#nesting)*, *[custom selectors](http://cssnext.io/features/#custom-selectors)* and *[custom variables](http://cssnext.io/features/#custom-properties-var)*. 

The implementation of said features could lead to the closing of this issue.

**Comment by tlrobinson** [comment]
Also, [CSS Modules](http://glenmaddern.com/articles/css-modules), e.x. the `composes` keyword.

**Comment by MoOx** [comment]
`composes` is not in CSS specs while nesting and other stuff mentionned are.

**Comment by thangngoc89** [comment]
Here is a snippet that atom can't highlight correctly:

```css
@custom-media --lg screen and (max-width: 1100px);
@custom-media --md screen and (max-width: 900px);
@custom-media --sm screen and (max-width: 500px);

.sidebar {
  lost-column: 1/3;

  @media (--lg) {
    lost-column: 2/4;
  }
  @media (--md) {
    lost-column: 5/12;
  }
  @media (--sm) {
    lost-column: 4/4;
  }
}

.sidebar-inner {
  position: relative;
	padding: 40px;

  @media (--lg) {
    padding: 35px 20px 0;
  }
  @media (--md) {
    padding: 30px 20px 0;
  }
  @media (--sm) {
    padding: 25px 20px 0;
  }
}
```

![image](https://cloud.githubusercontent.com/assets/3049054/14212643/14e9fcf8-f85e-11e5-9d84-dd6f3e2c7da3.png)
