### ISSUE TITLE
Confusion about quoted strings on long lines

### ISSUE THREAD

**Issue by danfuzz** [atom/language-css#87]
I'm not 100% sure what's going on, but as an example, the following gets improperly syntax highlighted:

```css
p::before {
  content: counter(a) "." counter(b) "." counter(c) "." counter(d) "." counter(e) "." counter(f) "." counter(g) "." counter(h) "." counter(i) "." counter(j) "." counter(k) "." counter(l);
}
```

In particular, `counter(l);` gets highlighted as if it is part of a quoted string instead of being marked up like the earlier `counter` invocations. See attached image.

FWIW, I distilled this example from actual CSS code I was working on.

<img width="1038" alt="quoted-counter" src="https://cloud.githubusercontent.com/assets/1090235/18371737/bb71b754-75eb-11e6-954b-d6f318ab928f.png">
