### ISSUE TITLE
“at-rule” rules treated as text

### ISSUE THREAD

**Issue by thomaslindstrom** [atom/language-css#9]
``` css
@media (min-resolution: 192dpi) {
    width: 200px;
    height: 200px; 
}
```

Whatever comes after `{` is treated as normal text when prepended by an `at-rule`, eg., media query. Replacing `@media (min-resolution: 192dpi)` with `.selector` “fixes” the highlighting.
